before:
  hooks:
  - yarn install
  - parcel build -d assets index.html
  - govendor sync
  - go run service/vfs/generate.go
builds:
- main: ./service/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
- main: ./service/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -H windowsgui -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archive:
  files:
  - LICENSE
  - USAGE.md
  - examples/*
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
git:
  short_hash: true
snapshot:
  name_template: "{{ .Tag }}-next"
