before:
  hooks:
  - govendor sync
  - parcel build -d assets index.html
builds:
- main: ./service/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  hooks:
    pre: go run service/vfs/generate.go
archive:
  files:
  - LICENSE
  - USAGE.md
  - examples/*
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
git:
  short_hash: true
snapshot:
  name_template: "{{ .Tag }}-next"
